[build]
builder = "NIXPACKS"
buildCommand = """
if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; elif [ -f requirements.txt ]; then pip install -r requirements.txt; fi
if [ -d frontend ]; then
  bash -lc 'cd frontend && (npm ci || npm install) && npm run build'
  mkdir -p backend/app/static
  cp -r frontend/dist/* backend/app/static/
fi
"""

[deploy]
startCommand = "bash backend/start.sh"
healthcheckPath = "/healthz"
restartPolicyType = "ON_FAILURE"
