[build]
builder = "NIXPACKS"
buildCommand = """
pip install -r backend/requirements.txt
if [ -d frontend ]; then
  bash -lc 'cd frontend && (npm ci || npm install) && npm run build'
  mkdir -p backend/app/static
  cp -r frontend/dist/* backend/app/static/
fi
"""

[deploy]
startCommand = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port ${PORT:-8080}"
healthcheckPath = "/healthz"
restartPolicyType = "ON_FAILURE"